development:
  adapter: postgresql
  encoding: unicode
  database: rails2_skeleton_app_development
  pool: 5
  username: bsmuser
  password: password
  host: /var/run/postgresql
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: rails2_skeleton_app_test
  pool: 5
  username: bsmuser
  password: password
  host: /var/run/postgresql
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: rails2_skeleton_app_development
  pool: 5
  username: bsmuser
  password: password
  host: /var/run/postgresql
  port: 5433
