defaults: &defaults
  host: localhost
  slaves:
    - host: slave1.local
      port: 27018
    - host: slave2.local
      port: 27019
  autocreate_indexes: false
  allow_dynamic_fields: false
  include_root_in_json: false
  parameterize_keys: true
  persist_in_safe_mode: true
  raise_not_found_error: true
  reconnect_time: 3

development:
  <<: *defaults
  database: control_development

test:
  <<: *defaults
  database: control_test

# set these environment variables on your prod server
production:
  <<: *defaults
  host: flame.mongohq.com
  port: 27086
  database: app253830
  username: app253830
  password: 321t1f96urmjyvshd5clod